# Generated by Django 6.1.1 on 2026-09-07 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CHECK_IN', 'Check In'), ('QUEUE', 'Queue'), ('CANCELLATION', 'Cancellation')], max_length=20)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_SERVICE', 'In Service'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_wait_time', models.PositiveIntegerField(default=0, help_text='Estimated waiting time in minutes')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
