# Generated by Django 6.1.1 on 2026-09-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_name_appointment_username'),
        ('queue_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='patient',
        ),
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['queue_number']},
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='estimated_wait_time',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='patient',
        ),
        migrations.AddField(
            model_name='queueentry',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='consultation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('appointment', 'queue_number'), name='unique_queue_entry_number'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
