# Generated by Django 6.1.1 on 2026-09-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_name_appointment_username'),
        ('notifications', '0001_initial'),
        ('queue_management', '0002_remove_notification_patient_alter_queueentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('CHECKED_IN', 'Checked In'), ('ALMOST_TURN', 'Almost Your Turn'), ('YOUR_TURN', 'Your Turn')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('appointment', 'notification_type'), name='unique_appointment_notification_type'),
        ),
    ]
