# Generated by Django 6.1.1 on 2026-10-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('CHECKED_IN', 'Checked In'), ('ALMOST_TURN', 'Almost Your Turn'), ('YOUR_TURN', 'Your Turn'), ('FEEDBACK_ADDED', 'Feedback Added')], max_length=30),
        ),
    ]
